branch-defaults:
  master:
    environment: flask-aws-tutorial-master-env
global:
  application_name: flask-aws-tutorial-master
  branch: null
  default_ec2_keyname: null
  default_platform: Python 2.7
  default_region: ap-southeast-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
